name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  run_tests_ubuntu:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: environment.yaml
      - shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Run pytest
        run: |
          pytest -v

  # upload code coverage report
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
          environment-file: environment.yaml

      - name: Run tests and collect coverage
        # NEEDS TO BE UPDATED WHEN CHANGING THE NAME OF "src" FOLDER
        run: |
          pip install pytest-cov[toml]
          pytest --cov src

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
